[application]
# Asset directory for the app crate
asset_dir = "crates/coppermind/public"

[bundle]
identifier = "dev.errorsignal"
publisher = "Matthew Emerson"

[web.watcher]
# When watcher is triggered, regenerate the `index.html`
reload_html = true
# Which files or dirs will be monitored
watch_path = ["crates/coppermind/src", "crates/coppermind/public", "crates/coppermind-core/src"]

[web.app]
base_path = "/coppermind"
# HTML title tag content
title = "Coppermind"

[web.resource]
# Additional CSS style files
style = []
# Additional JavaScript files
script = []
#script = ["public/coi-serviceworker.min.js"]

[web.resource.dev]
# Javascript code file
# serve: [dev-server] only
script = []
